using WebApi.Models.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApi.Models.Models.Users
{
    /// <summary>
    /// Represents user authentication in the system.
    /// </summary>
    [Table("Authentication")]
    public class Authentication
    {
        /// <summary>
        /// Unique identifier for the user's authentication record.
        /// Automatically generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// User's email address or CPF used for login.
        /// </summary> 
        [Required]
        public string Login { get; set; } = string.Empty;

        /// <summary>
        /// User's password, securely stored.
        /// </summary>
        [Required]
        public string Password { get; set; } = string.Empty;

        /// <summary>
        /// User profile, determining access level in the system.
        /// </summary>
        [Required]
        public EProfile Profile { get; set; }
    }
}
