using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApi.Models.Models.Users
{
    /// <summary>
    /// Represents the additional curiosity layers linked to a specific User.
    /// Stores extended information such as other facts, interests, and feelings.
    /// </summary>
    [Table("Curiosity")]
    public class Curiosity
    {
        /// <summary>
        /// Unique identifier for the curiosity record.
        /// Automatically generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Foreign key reference to the User entity (1–1 relationship).
        /// </summary>
        [Required]
        public long UserId { get; set; } 
         
        /// <summary>
        /// Additional free-text information about the user.
        /// </summary>
        [MaxLength(2000)]
        public string? OtherInfo { get; set; }

        /// <summary>
        /// User's interests, stored as free text.
        /// </summary>
        [MaxLength(4000)]
        public string? Interests { get; set; }

        /// <summary>
        /// User's feelings, stored as free text.
        /// </summary>
        [MaxLength(4000)]
        public string? Feelings { get; set; }

        /// <summary>
        /// Timestamp of when the curiosity record was created.
        /// Defaults to the current UTC date and time.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Timestamp of the last update for this curiosity record.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }


        /// <summary>
        /// Navigation property for the associated User.
        /// </summary>
        [ForeignKey(nameof(UserId))]
        public virtual User User { get; set; } = default!;
    }
}
